# Generated by Django 4.2.30 on 2026-09-25 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_support_groups_ab'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USUARIO_CREADO', 'Usuario creado'), ('USUARIO_EDITADO', 'Usuario editado'), ('USUARIO_DESACTIVADO', 'Usuario desactivado'), ('USUARIO_ACTIVADO', 'Usuario activado'), ('ROL_CAMBIADO', 'Rol cambiado'), ('CARGA_MASIVA', 'Carga masiva de usuarios'), ('RESET_SOLICITADO', 'Restablecimiento solicitado'), ('RESET_COMPLETADO', 'Contraseña restablecida'), ('CUENTA_BLOQUEADA', 'Cuenta bloqueada'), ('CATALOGO_CREADO', 'Catálogo creado'), ('CATALOGO_EDITADO', 'Catálogo editado'), ('REPORTE_DESCARGADO', 'Reporte descargado')], db_index=True, max_length=30)),
                ('entidad', models.CharField(blank=True, default='', max_length=60)),
                ('entidad_id', models.CharField(blank=True, default='', max_length=60)),
                ('detalle', models.TextField(blank=True, default='')),
                ('ip', models.CharField(blank=True, default='', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx')],
            },
        ),
    ]
