# Generated by Django 4.2.30 on 2026-08-23 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FTTH', 'FTTH'), ('HFC', 'HFC'), ('DTH', 'DTH'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20)),
                ('priority', models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=12)),
                ('status', models.CharField(choices=[('ABIERTO', 'Abierto'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En proceso'), ('VALIDACION', 'Validación'), ('CERRADO', 'Cerrado'), ('ESCALADO', 'Escalado')], default='ABIERTO', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('sla_due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('validation_due_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to='accounts.team')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('origin_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_tickets', to='accounts.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREADO', 'Creado'), ('ASIGNADO', 'Asignado'), ('TOMADO', 'Tomado por soporte'), ('RESUELTO', 'Enviado a validación'), ('APROBADO', 'Solución aprobada'), ('RECHAZADO', 'Solución rechazada'), ('ESCALADO', 'Escalado por SLA'), ('AUTO_CERRADO', 'Cerrado automáticamente'), ('ADJUNTO', 'Evidencia adjunta')], max_length=20)),
                ('from_status', models.CharField(blank=True, choices=[('ABIERTO', 'Abierto'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En proceso'), ('VALIDACION', 'Validación'), ('CERRADO', 'Cerrado'), ('ESCALADO', 'Escalado')], max_length=20)),
                ('to_status', models.CharField(blank=True, choices=[('ABIERTO', 'Abierto'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En proceso'), ('VALIDACION', 'Validación'), ('CERRADO', 'Cerrado'), ('ESCALADO', 'Escalado')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_events', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='tickets_tic_status_b256f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_team', 'status'], name='tickets_tic_assigne_f5223a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['creator', 'status'], name='tickets_tic_creator_cc6043_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sla_due_at'], name='tickets_tic_sla_due_03e0df_idx'),
        ),
    ]
