# Generated by Django 4.2.14 on 2026-09-14 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CLIENTE', 'Solicitud de Soporte Cliente'), ('TECNICO', 'Soporte Al Tecnico')], max_length=10)),
                ('service', models.CharField(choices=[('HFC', 'HFC'), ('FTTH', 'FTTH'), ('WTTX', 'WTTX'), ('DTH', 'DTH')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de solicitud',
                'verbose_name_plural': 'tipos de solicitud',
                'ordering': ['kind', 'service', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_nombre',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='ticket',
            name='identificador',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nodo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('FTTH', 'FTTH'), ('HFC', 'HFC'), ('DTH', 'DTH'), ('WTTX', 'WTTX'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['identificador', 'status'], name='tickets_tic_identif_e86b52_idx'),
        ),
        migrations.AddConstraint(
            model_name='requesttype',
            constraint=models.UniqueConstraint(fields=('kind', 'service', 'name'), name='unique_request_type'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.requesttype'),
        ),
    ]
