# Generated by Django 4.2.14 on 2026-09-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_seed_request_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('ASIGNADO', 'Asignado'), ('TOMADO', 'Tomado por soporte'), ('RESUELTO', 'Enviado a validación'), ('APROBADO', 'Solución aprobada'), ('RECHAZADO', 'Solución rechazada'), ('ESCALADO', 'Escalado por SLA'), ('AUTO_CERRADO', 'Cerrado automáticamente'), ('ADJUNTO', 'Evidencia adjunta'), ('LIBERADO', 'Liberado a bandeja')], max_length=20),
        ),
    ]
