# Generated by Django 4.2.30 on 2026-09-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_escalamiento'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_contrat_43f4bf_idx',
            old_name='tickets_contrato_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_numero__0e85cb_idx',
            old_name='tickets_numeroot_status_idx',
        ),
    ]
