# Generated by Django 4.2.30 on 2026-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_rename_tickets_contrato_status_idx_tickets_tic_contrat_43f4bf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='ocr_estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de OCR'), ('PROCESANDO', 'Procesando texto'), ('OK', 'Texto extraído'), ('FALLIDO', 'No se pudo extraer')], default='PENDIENTE', max_length=12),
        ),
    ]
