# Generated by Django 4.2.30 on 2026-09-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_support_groups_ab'),
        ('tickets', '0007_ticketattachment_ocr_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='equipo_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_asignados', to='accounts.team'),
        ),
    ]
