# Generated by Django 4.2.30 on 2026-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_requesttype_equipo_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('ASIGNADO', 'Asignado'), ('TOMADO', 'Tomado por soporte'), ('INICIADO', 'Atención iniciada'), ('RESUELTO', 'Enviado a validación'), ('APROBADO', 'Solución aprobada'), ('RECHAZADO', 'Solución rechazada'), ('ESCALADO', 'Escalado'), ('DESESCALADO', 'Vuelto de escalamiento'), ('INSTRUCCION', 'Instrucciones de despacho'), ('AUTO_CERRADO', 'Cerrado automáticamente'), ('ADJUNTO', 'Evidencia adjunta'), ('LIBERADO', 'Liberado a bandeja')], max_length=20),
        ),
    ]
