# Generated by Django 4.2.30 on 2026-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticketevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='kind',
            field=models.CharField(choices=[('EVIDENCIA', 'Evidencia inicial'), ('SOLUCION', 'Evidencia de solución')], default='EVIDENCIA', max_length=10),
        ),
    ]
