# Generated by Django 4.2.30 on 2026-09-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticketattachment_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='campos_ocr',
            field=models.CharField(blank=True, default='', help_text='Etiquetas separadas por coma que el OCR debe buscar (ej. SN,MAC). Vacío = genérico.', max_length=200),
        ),
    ]
